import subprocess as sp
import pymysql
import pymysql.cursors
from os import get_terminal_size
from fns import fn1, fn2, fn3, fn4, fn5, fn6, fn7, fn8, fn9, fn10, fn11, fn12, fn13, fn14

def dispatch(x):
    if x == 1:
        fn1()
    elif x == 2:
        fn2()
    elif x == 3:
        fn3()
    elif x == 4:
        fn4()
    elif x == 5:
        fn5()
    elif x == 6:
        fn6()
    elif x == 7:
        fn7()
    elif x == 8:
        fn8()
    elif x == 9:
        fn9()
    elif x == 10:
        fn10()
    elif x == 11:
        fn11()
    elif x == 12:
        fn12()
    elif x == 13:
        fn13()
    elif x == 14:
        fn14()

sp.call('cls', shell=True)
hell1 = [
r"+-+-+-+-+-+-+-+   +-+-+",
r"|W|e|l|c|o|m|e|   |t|o|",
r"+-+-+-+-+-+-+-+   +-+-+"]

hell3 = [r"  _       __   ______      __        ",
         r" | |     / /__/_  __/_  __/ /_  ___  ",
         r" | | /| / / _ \/ / / / / / __ \/ _ \ ",
         r" | |/ |/ /  __/ / / /_/ / /_/ /  __/ ",
         r" |__/|__/\___/_/  \__,_/_.___/\___/  "]

centered1 = [line.center(get_terminal_size().columns) for line in hell1]
centered2 = [line.center(get_terminal_size().columns) for line in hell3]
menulogo1 = '\n'.join(centered1)
menulogo2 = '\n'.join(centered2)

print(menulogo1)
print(menulogo2)

try:
    # Set db name accordingly which have been create by you
    # Set host to the server's address if you don't want to use local SQL server
    connnection = pymysql.connect(host='localhost',
                                  user="root",
                                  password="<password>",
                                  db="daproj",
                                  cursorclass=pymysql.cursors.DictCursor)

    if connnection.open:
        print("Connected to the database!\n")
    else:
        print("Failed to connect to the database :(")

    with connnection.cursor() as cur:
        tmp = input("> Press enter to continue")
        while 1:
            sp.call('cls', shell=True)

            # updates
            print("1.  Upload a video")  # insert
            print("2.  Change the title of a video")  # update
            print("3.  Delete a comment\n")  # delete

            # queries
            print("4.  List all videos uploaded by an account")
            print("5.  Find all accounts that have more than N subscribers")
            print("6.  Average advertisement revenue generated by an account per video")
           
            print("7.  Search for an account")
            print("8.  Get like-dislike ratio of a certain account's videos")

            print("9.  Get all videos with more than a million views")
            print("10. Total watchtime of an account")
            print("11. Video with the most and least views on an account")

            print("12. Search for a video")

            print("13. Generate revenue report for an account")
            print("14. Find out engagement statistics for videos")

            print("\n\n\t\t*** Enter 0 to logout ***\n")

            while True:
                try:
                    ch = int(input("Enter choice: "))
                    break
                except:
                    print("Please enter a valid choice")
                    continue

            sp.call('cls', shell=True)

            if ch == 0:
                break

            dispatch(ch)
            tmp = input("\n\n\n\n> Press enter to continue")


except Exception:
    print("Unable to connect to the server.")
